name: Lint
on:
  pull_request:
      branches: [dev]
jobs:
  run-lint:
      name: Run linters
      runs-on: ubuntu-latest

      steps:
        - name: Check outs
          uses: actions/checkout@v2

        - name: Install yarn
          run: yarn install

        - name: Run lint
          run: yarn lint